### ISSUE TITLE
Everythign "unknown"

### ISSUE THREAD

**Issue by TheBartoMan** [gadget-man/iparcelboxHA#6] opened 2023-09-06 09:33 UTC
Everything in "unknown" suck as parcel count, last opened etc.

but i can still click the buttons like "allow delivery" and they work.

Any ideas please? restarted the iparcelbox and restarted home assistant.

**Comment by gadget-man** [comment] 2023-09-06 09:35
Have you recently updated HA? If so, please can you confirm what version you are running?   Also, please turn on debugging for the iParcelBox integration and check the logs when you reboot HA to see if anything shows.

**Comment by TheBartoMan** [comment] 2023-09-06 09:49
Everything in Home Assistant is up to date and the latest version as of today. (Can’t recall when it stopped working sorry)

I turned on debugging and restarted home assistant.

I then searched the home assistant logs for “iparcel” and the attached image shows the results. (I’ve obfuscated various details and not sure I should post them)

Regards

From: gadget-man ***@***.***>
Date: Wednesday, 6 September 2023 at 10:35
To: gadget-man/iparcelboxHA ***@***.***>
Cc: TheBartoMan ***@***.***>, Author ***@***.***>
Subject: Re: [gadget-man/iparcelboxHA] Everythign "unknown" (Issue #6)

Have you recently updated HA? If so, please can you confirm what version you are running? Also, please turn on debugging for the iParcelBox integration and check the logs when you reboot HA to see if anything shows.

**Comment by gadget-man** [comment] 2023-09-07 09:34
I didn't get any details of the screenshot - please could you send it through to our customer support email and we can take a look for you?

**Comment by TheBartoMan** [comment] 2023-09-07 09:57
![iparcel](https://github.com/gadget-man/iparcelboxHA/assets/28529964/d3c9891b-0f33-46d5-9d51-c6744d987bf8)
Here you go. Doesnt seem to be any issues I can see though. Thanks.

**Comment by gadget-man** [comment] 2023-09-07 10:18
it looks as though everything is working as expected - we can see that the web hook request provides a response from the controller.

I suspect this is something unique to your configuration, rather than an issue with the integration itself - please contact us using the normal iParcelBox support channels (email, chat etc) and we can look into this further for you.

**Comment by gadget-man** [comment] 2023-09-08 09:40
Closing this, as confirmed this was an issue linked to the user's HA configuration, not a bug.

For other users encountering similar issues, make sure that the web hook that appears in the logs doesn't reference a url / domain name that may not be recognised or accessible locally.

**Closed as completed by gadget-man** 2023-09-08 09:40 UTC
